# Mirrors scripts/build-pure-html.mjs — no Node required.
# Run from repo root: powershell -ExecutionPolicy Bypass -File scripts/build-pure-html.ps1
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$evPath = Join-Path $root "data\events.json"
$tplPath = Join-Path $root "scripts\pure-template.html"
$outPath = Join-Path $root "immba-pure.html"

function Esc([string]$s) {
  if ($null -eq $s) { return "" }
  return (($s -replace '&', '&amp;') -replace '<', '&lt;') -replace '>', '&gt;' -replace '"', '&quot;'
}
function EscAttr([string]$s) {
  return ((Esc $s) -replace "'", '&#39;')
}
function EventDateMs([string]$s) {
  $t = 0
  try { $t = [DateTimeOffset]::Parse($s.Trim()).ToUnixTimeMilliseconds() } catch { $t = 0 }
  return $t
}

$u8 = New-Object System.Text.UTF8Encoding $false
$evFileUtf8 = [System.IO.File]::ReadAllText($evPath, $u8)
$data = $evFileUtf8 | ConvertFrom-Json
$eventsEmbedJson = $evFileUtf8.Trim()

$norm = @()
foreach ($raw in $data.events) {
  $title = [string]$raw.title
  $date = [string]$raw.date
  $body = if ($raw.body) { [string]$raw.body } elseif ($raw.content) { [string]$raw.content } else { "" }
  $imageUrl = ""
  if ($raw.image -and [string]$raw.image.Trim()) { $imageUrl = [string]$raw.image.Trim() }
  elseif ($raw.imageUrl -and [string]$raw.imageUrl.Trim()) { $imageUrl = [string]$raw.imageUrl.Trim() }
  if (-not $title.Trim() -or -not $date.Trim()) { continue }
  $hashtags = @()
  if ($raw.hashtags) { $hashtags = @($raw.hashtags | ForEach-Object { [string]$_ }) | Where-Object { $_.Trim() } }
  $titleEn = if ($raw.titleEn) { [string]$raw.titleEn.Trim() } else { "" }
  $bodyEn = if ($raw.bodyEn) { [string]$raw.bodyEn } elseif ($raw.contentEn) { [string]$raw.contentEn } else { "" }
  $bodyEn = $bodyEn.Trim()
  $dateZh = if ($raw.dateZh) { [string]$raw.dateZh.Trim() } else { "" }
  $norm += [PSCustomObject]@{
    title = $title.Trim()
    date = $date.Trim()
    body = $body
    imageUrl = $imageUrl
    hashtags = $hashtags
    titleEn = $titleEn
    bodyEn = $bodyEn
    dateZh = $dateZh
  }
}
$events = $norm | Sort-Object { EventDateMs $_.date } -Descending

$cards = New-Object System.Collections.Generic.List[string]
foreach ($ev in $events) {
  $imgBlock = ""
  if ($ev.imageUrl) {
    $a = EscAttr $ev.imageUrl
    $imgBlock = @"
      <div class="pure-event-card__media">
        <img class="pure-event-card__img" src="$a" alt="" width="1200" height="750" loading="lazy" decoding="async" />
      </div>
"@
  }
  $tagBlock = ""
  if ($ev.hashtags -and $ev.hashtags.Count -gt 0) {
    $tagLine = ($ev.hashtags | ForEach-Object { Esc $_ }) -join " "
    if ($tagLine) { $tagBlock = "`n        <p class=`"pure-event-card__hashtags`">$tagLine</p>" }
  }
  $titleEnBlock = ""
  if ($ev.titleEn) { $titleEnBlock = "`n        <p class=`"pure-event-card__title-en`" lang=`"en`">$(Esc $ev.titleEn)</p>" }
  $bodyEnBlock = ""
  if ($ev.bodyEn) { $bodyEnBlock = "`n        <div class=`"pure-event-card__content-en`" lang=`"en`">$(Esc $ev.bodyEn)</div>" }
  $dateLine = if ($ev.dateZh) { Esc $ev.dateZh } else { Esc $ev.date }
  $cards.Add(@"
      <article class="pure-event-card">
$imgBlock
      <div class="pure-event-card__body">
        <h3 class="pure-event-card__title">$(Esc $ev.title)</h3>$titleEnBlock
        <div class="pure-event-card__date">$dateLine</div>
        <div class="pure-event-card__content">$(Esc $ev.body)</div>$bodyEnBlock$tagBlock
      </div>
    </article>
"@)
}
$eventCards = $cards -join "`n"

$html = [System.IO.File]::ReadAllText($tplPath, $u8)
$html = $html.Replace("<!--INJECT_META_COMMENT-->", "<!-- Generated by scripts/build-pure-html.ps1 or npm run build:pure -->")
$html = $html.Replace("<!--INJECT_EVENTS-->", $eventCards)
$html = $html.Replace("<!--INJECT_EVENTS_EMBED_JSON-->", $eventsEmbedJson)
$GALLERY_URL = "https://www.management.fju.edu.tw/subweb/immba/subedit.php?EID=241"
$html = $html.Replace("GALLERY_URL_PLACEHOLDER", (EscAttr $GALLERY_URL))
[System.IO.File]::WriteAllText($outPath, $html, $u8)
Write-Host "Wrote" $outPath
